### ISSUE TITLE
Not able to set different lengths for fingerprints

### ISSUE THREAD

**Issue by projectmx3** [rdkit/rdkit-js#482] opened 2024-08-11 18:47 UTC
**Describe the bug**
It doesn't seem to be possible to set different lengths for fingerprints. They are all returning as 2048.

**To Reproduce**

const morganOptions = JSON.stringify({ radius: 3, len: 8192 });
const morganFingerprint = mol.get_morgan_fp(morganOptions);

run

console.log("Morgan Fingerprint Length:", morganFingerprint.length);

result = 2048.

Tried this across all the fingerprint types, and also tried using 'len' and 'fplen' and always get 2048 for the length.

**Expected behavior**
Expect the fingerprints to be set to the requisite length.
Expected result = 8192.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Latest

**Comment by ptosco** [comment] 2024-08-11 20:06
The problem is that you are not using the correct parameter name, which is `nBits`.
You may look up the parameter names in the `Code/MinimalLib/tests/tests.js` file, e.g.:
https://github.com/rdkit/rdkit/blob/5771d9c18192c48a9895b8993a18b53ea43ab663/Code/MinimalLib/tests/tests.js#L92

Closing as this is not a bug.

**Closed by ptosco** 2024-08-11 20:06 UTC

**Comment by projectmx3** [comment] 2024-08-12 00:37
Thanks so much. It's working. I had got "len" from the docs here:

https://docs.rdkitjs.com/interfaces/JSMol.html#get_morgan_fp
#
Returns string

    Defined in index.d.ts:123

get_morgan_fp_as_binary_text(radius, len): string
